{% set name = "model_bakery" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2f0522a4b7d3cc1b6f88e95ac87cefd9317516274bb126f54488f47fe3aaafd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - django >=1.11.0
    - python

test:
  imports:
    - model_bakery

about:
  home: http://github.com/model-bakers/model_bakery
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Smart object creation facility for Django.
  doc_url: https://pypi.org/project/model-bakery/
  dev_url: https://github.com/model-bakers/model_bakery

extra:
  recipe-maintainers:
    - oblute
    - benhuff
